n = input("Digite algo: ")
print('Qual é o tipo primitivo?: {}'.format(type(n)))
print('O valor esta todo em maiusculo?: {}'.format(n.isupper()))
print('O valor esta todo em minusculo?: {}'.format(n.islower()))
print('O valor contem letras e numeros?: {}'.format(n.isalnum()))
print('O valor é uma letra?: {}'.format(n.isalpha()))
print('O valor faz parte da tabela ASCII?: {}'.format(n.isascii()))
print('O valor é um digito?: {}'.format(n.isdigit()))
print('O valor é um numero decimal?: {}'.format(n.isdecimal()))
print('O valor é valido para ser um identificador em python?: {}'.format(n.isidentifier()))
print('O valor é um numero?: {}'.format(n.isnumeric()))
print('isprintable: {}'.format(n.isprintable()))
print('O valor esta todo em branco?: {}'.format(n.isspace()))
print('O valor esta formatodo de titulo?: {}'.format(n.istitle()))